[package]
name = "windows-install-rust-gdal-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdal = "0.16.0"
chrono = "0.4"


