name: SET GDAL ENV

on:
    push:
      branches: [main]

jobs:
  env:
    runs-on: windows-latest
    name: GDAL ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build deps and run test
        shell: pwsh
        run: |
          ./scripts/env.ps1
          rustup install stable
          rustup component add rustfmt clippy
          cargo run --example metadata 