name: SET GDAL ENV

on:
    push:
      branches: [main]

jobs:
  env:
    runs-on: windows-latest
    name: GDAL ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build deps
        shell: pwsh
        run: |
          ./scripts/env.ps1
      - name: Install stable
        run: |
            rustup install stable
            rustup component add rustfmt clippy
      - name: Run Test
        run: cargo run --example metadata 