name: Rust GDAL IN Windows

on:
    push:
      branches: [main]

jobs:
  env:
    runs-on: windows-latest
    name: GDAL ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build deps and run test
        shell: pwsh
        run: |
          ./scripts/env.ps1
          ls
          cargo run --example metadata 